"use client"
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { 
  Leaf,
  DollarSign,
  TrendingUp,
  TrendingDown,
  Brain,
  BarChart3,
  CloudRain,
  Sun,
  Target,
  Clock,
  Droplets,
  MapPin,
  AlertTriangle,
  CheckCircle2,
  Calendar,
  ShieldCheck,
  Zap,
  BookOpen
} from 'lucide-react';

const CropRecommendationPage = () => {

  // AI-driven summary of environmental and market factors
  const keyFactors = {
    weather: { title: "Weather Outlook (Kharif)", summary: "Above-average monsoon predicted", detail: "+15% rainfall expected, favouring water-intensive crops.", icon: <CloudRain className="h-8 w-8 text-blue-100" /> },
    soil: { title: "Soil Health Analysis", summary: "Nitrogen levels optimal", detail: "Loamy soil, pH 6.8. Ideal for cereals and legumes.", icon: <Zap className="h-8 w-8 text-yellow-100" /> },
    water: { title: "Water Availability", summary: "High reservoir levels", detail: "Canal water supply is rated 'Excellent' for the upcoming season.", icon: <Droplets className="h-8 w-8 text-cyan-100" /> },
    market: { title: "Market & MSP Trends", summary: "Pulses market bullish", detail: "Government MSP for pulses increased by 6%. Strong export demand.", icon: <TrendingUp className="h-8 w-8 text-green-100" /> },
  };

  // Top 3 crop recommendations generated by the AI model
  const topRecommendations = [
    {
      rank: 1,
      name: 'Basmati Rice (Pusa-1121)',
      suitability: 96,
      profitability: '₹ 95,000 - ₹ 1,15,000',
      reasoning: "Excellent match for predicted rainfall. High MSP and strong global demand ensure high profitability.",
      metrics: {
        yield: '5.5 tons/hectare',
        msp: '₹ 4,800/quintal',
        duration: '140-145 days',
        waterNeed: 'High'
      },
      pros: ['Highest Profit Potential', 'Guaranteed MSP Buy', 'Well-suited to local soil'],
      cons: ['High Water Requirement', 'Pest Susceptible'],
      badge: 'Top Pick'
    },
    {
      rank: 2,
      name: 'Maize (Hybrid HQPM-1)',
      suitability: 89,
      profitability: '₹ 70,000 - ₹ 85,000',
      reasoning: "Drought-resistant variety provides a safe option. Rising demand in poultry feed market.",
      metrics: {
        yield: '7.0 tons/hectare',
        msp: '₹ 2,090/quintal',
        duration: '110-120 days',
        waterNeed: 'Medium'
      },
      pros: ['Lower Water Usage', 'Short Duration', 'High Yield Variety'],
      cons: ['Market Price Fluctuation', 'Lower MSP than Rice'],
      badge: 'Balanced Choice'
    },
    {
      rank: 3,
      name: 'Moong Bean (Pusa Vishal)',
      suitability: 85,
      profitability: '₹ 65,000 - ₹ 78,000',
      reasoning: "Short duration allows for multi-cropping. Fixes soil nitrogen, improving farm health.",
      metrics: {
        yield: '1.2 tons/hectare',
        msp: '₹ 8,558/quintal',
        duration: '60-70 days',
        waterNeed: 'Low'
      },
      pros: ['Very Low Water Need', 'Improves Soil Fertility', 'Extremely Short Cycle'],
      cons: ['Lower Overall Yield', 'Sensitive to Waterlogging'],
      badge: 'Smart Rotation'
    }
  ];

  const getWaterNeedColor = (need: string) => {
    switch (need.toLowerCase()) {
      case 'high': return 'text-blue-600';
      case 'medium': return 'text-yellow-600';
      case 'low': return 'text-green-600';
      default: return 'text-gray-600';
    }
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">AI Crop Cycle Recommendations</h1>
          <div className="flex items-center justify-between">
            <div className="flex items-center text-gray-600">
              <MapPin className="h-4 w-4 mr-1" />
              <span className="text-sm">Jalandhar, Punjab • Kharif Season Planning</span>
            </div>
            <div className="flex items-center space-x-2">
              <Brain className="h-4 w-4 text-green-600" />
              <span className="text-sm font-medium text-green-600">Profitability Model: 92% Accuracy</span>
            </div>
          </div>
        </div>

        {/* Key Decision Factors */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
          <Card className="bg-gradient-to-br from-blue-500 to-blue-600 text-white">
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-blue-100 font-medium">{keyFactors.weather.title}</p>
                  <p className="text-xl font-bold">{keyFactors.weather.summary}</p>
                </div>
                {keyFactors.weather.icon}
              </div>
              <p className="text-blue-100 text-xs mt-2">{keyFactors.weather.detail}</p>
            </CardContent>
          </Card>
          <Card className="bg-gradient-to-br from-yellow-500 to-yellow-600 text-white">
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-yellow-100 font-medium">{keyFactors.soil.title}</p>
                  <p className="text-xl font-bold">{keyFactors.soil.summary}</p>
                </div>
                {keyFactors.soil.icon}
              </div>
              <p className="text-yellow-100 text-xs mt-2">{keyFactors.soil.detail}</p>
            </CardContent>
          </Card>
          <Card className="bg-gradient-to-br from-cyan-500 to-cyan-600 text-white">
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-cyan-100 font-medium">{keyFactors.water.title}</p>
                  <p className="text-xl font-bold">{keyFactors.water.summary}</p>
                </div>
                {keyFactors.water.icon}
              </div>
              <p className="text-cyan-100 text-xs mt-2">{keyFactors.water.detail}</p>
            </CardContent>
          </Card>
          <Card className="bg-gradient-to-br from-green-500 to-green-600 text-white">
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-green-100 font-medium">{keyFactors.market.title}</p>
                  <p className="text-xl font-bold">{keyFactors.market.summary}</p>
                </div>
                {keyFactors.market.icon}
              </div>
              <p className="text-green-100 text-xs mt-2">{keyFactors.market.detail}</p>
            </CardContent>
          </Card>
        </div>

        {/* Crop Recommendations */}
        <div>
          <h2 className="text-2xl font-bold text-gray-800 mb-4 flex items-center">
            <Leaf className="h-6 w-6 mr-2 text-green-600" />
            Top 3 Crop Recommendations
          </h2>
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            {topRecommendations.map((crop) => (
              <Card key={crop.rank} className={`flex flex-col ${crop.rank === 1 ? 'border-2 border-green-500' : 'border-gray-200'}`}>
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <CardTitle className="text-xl">{crop.name}</CardTitle>
                    <div className={`px-3 py-1 rounded-full text-xs font-medium ${
                      crop.rank === 1 ? 'bg-green-100 text-green-800' : 'bg-blue-100 text-blue-800'
                    }`}>
                      {crop.badge}
                    </div>
                  </div>
                  <div className="flex items-baseline space-x-2">
                    <p className="text-lg font-semibold text-green-600">{crop.profitability}</p>
                    <p className="text-sm text-gray-500">/ hectare</p>
                  </div>
                </CardHeader>
                <CardContent className="flex-grow flex flex-col">
                  <div className="bg-blue-50 border border-blue-200 rounded-lg p-3 mb-4">
                    <div className="flex items-start space-x-2">
                      <Brain className="h-4 w-4 text-blue-600 mt-0.5 flex-shrink-0" />
                      <div>
                        <p className="text-sm font-medium text-blue-800">AI Recommendation</p>
                        <p className="text-xs text-blue-700">{crop.reasoning}</p>
                      </div>
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-4 text-sm mb-4">
                    <div className="flex items-center"><Target className="h-4 w-4 mr-2 text-gray-500" /><span className="font-medium">{crop.metrics.yield}</span></div>
                    <div className="flex items-center"><DollarSign className="h-4 w-4 mr-2 text-gray-500" /><span className="font-medium">{crop.metrics.msp}</span></div>
                    <div className="flex items-center"><Calendar className="h-4 w-4 mr-2 text-gray-500" /><span className="font-medium">{crop.metrics.duration}</span></div>
                    <div className="flex items-center"><Droplets className="h-4 w-4 mr-2 text-gray-500" /><span className={`font-medium ${getWaterNeedColor(crop.metrics.waterNeed)}`}>{crop.metrics.waterNeed}</span></div>
                  </div>

                  <div className="space-y-3 mb-4">
                    <div>
                      <h4 className="text-sm font-medium text-gray-800 mb-1">Pros</h4>
                      <ul className="space-y-1">
                        {crop.pros.map((pro, i) => (
                          <li key={i} className="flex items-center text-xs text-green-700">
                            <CheckCircle2 className="h-3 w-3 mr-2 flex-shrink-0" /> {pro}
                          </li>
                        ))}
                      </ul>
                    </div>
                    <div>
                      <h4 className="text-sm font-medium text-gray-800 mb-1">Cons</h4>
                      <ul className="space-y-1">
                        {crop.cons.map((con, i) => (
                          <li key={i} className="flex items-center text-xs text-red-700">
                            <AlertTriangle className="h-3 w-3 mr-2 flex-shrink-0" /> {con}
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>
                  
                  <div className="mt-auto">
                    <Button className="w-full bg-blue-600 hover:bg-blue-700 text-white">
                      <BookOpen className="h-4 w-4 mr-2" />
                      View Detailed Planting Guide
                    </Button>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
        
      </div>
    </div>
  );
};

export default CropRecommendationPage;